config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls',namespace="accounts")),
    path("students/",include("student.urls",namespace="student")),
    path("instructor/",include("instructor.urls",namespace="instructor"))
]


if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instructor/urls.py
from django.urls import path
from .views import instructor,createQuiz,createQestion,createQuizChoices,deleteQuiz

app_name = "instructor"

urlpatterns = [
    path("",instructor,name="instructor"),
    path("createQuiz/",createQuiz,name="createQuiz"),
    path("createQestion/",createQestion,name="createQestion"),
    path("createQuizChoices/",createQuizChoices,name="createQuizChoices"),
    path("deleteQuiz/<int:id>/",deleteQuiz,name="deleteQuiz")
]

student/urls.py
from django.urls import path
from .views import studentDashboard,quiz

app_name = "student"

urlpatterns = [
    path("",studentDashboard,name="studentDashboard"),
    path("quiz/",quiz,name="quiz")
   
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">

{% include 'head.html' %}


<body class="layout-default">



{% include 'header.html' %}

<div class="mdk-header-layout__content">

    <div class="mdk-drawer-layout js-mdk-drawer-layout" data-push data-responsive-width="992px">
        <div class="mdk-drawer-layout__content page">



            <div class="container-fluid page__heading-container">
                <div class="page__heading d-flex flex-column flex-md-row align-items-center justify-content-center justify-content-lg-between text-center text-lg-left">
                    <h1 class="m-lg-0">{% block name %}{% endblock name %}</h1>
                 
                </div>
            </div>
        
        
        
        
            {% block content %}{% endblock content %}
        
        </div>
        <!-- // END drawer-layout__content -->

        <div class="mdk-drawer  js-mdk-drawer" id="default-drawer" data-align="start">
            <div class="mdk-drawer__content">
                <div class="sidebar sidebar-light sidebar-left bg-white" data-perfect-scrollbar>


                    <div class="sidebar-block p-0 m-0">
                        <div class="d-flex align-items-center sidebar-p-a border-bottom bg-light">
                            <a href="#" class="flex d-flex align-items-center text-body text-underline-0">
                                <span class="avatar avatar-sm mr-2">
                                    <span class="avatar-title rounded-circle bg-soft-secondary text-muted">AD</span>
                                </span>
                                <span class="flex d-flex flex-column">
                                    <strong>Adrian Demian</strong>
                                    <small class="text-muted text-uppercase">Instructor</small>
                                </span>
                            </a>
                            <div class="dropdown ml-auto">
                                <a href="#" data-toggle="dropdown" data-caret="false" class="text-muted"><i class="material-icons">more_vert</i></a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="student-dashboard.html">Dashboard</a>
                                    <a class="dropdown-item" href="student-profile.html">My profile</a>
                                    <a class="dropdown-item" href="student-edit-account.html">Edit account</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" rel="nofollow" data-method="delete" href="login.html">Logout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sidebar-block p-0">

                           
                        <li class="sidebar-menu-item">
                            <a class="sidebar-menu-button" href="{% url 'student:studentDashboard' %}">
                                <i class="sidebar-menu-icon sidebar-menu-icon--left material-icons">tab</i>
                                <span class="sidebar-menu-text">Dashboard</span>
                            </a>
                        </li>
                          
                            <li class="sidebar-menu-item">
                                <a class="sidebar-menu-button" href="{% url 'student:quiz' %}">
                                    <i class="sidebar-menu-icon sidebar-menu-icon--left material-icons">tab</i>
                                    <span class="sidebar-menu-text">Take A Quiz</span>
                                </a>
                            </li>
                          
                        
                        
                        </ul>

    
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- // END drawer-layout -->

</div>

    <div class="mdk-drawer js-mdk-drawer" id="events-drawer" data-align="end">
        <div class="mdk-drawer__content">
            <div class="sidebar sidebar-light sidebar-left" data-perfect-scrollbar>




                <small class="text-dark-gray px-3 py-1">
                    <strong>Thursday, 28 Feb</strong>
                </small>

                <div class="list-group list-group-flush">

                    <div class="list-group-item bg-light">
                        <div class="row">
                            <div class="col-auto d-flex flex-column">
                                <small>12:30 PM</small>
                                <small class="text-dark-gray">2 hrs</small>
                            </div>
                            <div class="col">
                                <div class="d-flex flex-column flex">
                                    <a href="#" class="text-body"><strong class="text-15pt">Marketing Team Meeting</strong></a>

                                    <small class="text-muted d-flex align-items-center"><i class="material-icons icon-16pt mr-1">location_on</i> 16845 Hicks Road</small>


                                </div>
                                <div class="avatar-group mt-2">

                                    <div class="avatar avatar-xs">
                                        <img src="{% static 'assets/images/256_joao-silas-636453-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                    </div>

                                    <div class="avatar avatar-xs">
                                        <img src="{% static 'assets/images/256_jeremy-banks-798787-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                    </div>

                                    <div class="avatar avatar-xs">
                                        <img src="{% static 'assets/images/256_daniel-gaffey-1060698-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                <small class="text-dark-gray px-3 py-1">
                    <strong>Wednesday, 27 Feb</strong>
                </small>

                <div class="list-group list-group-flush">

                    <div class="list-group-item bg-light">
                        <div class="row">
                            <div class="col-auto d-flex flex-column">
                                <small>07:48 PM</small>
                                <small class="text-dark-gray">30 min</small>
                            </div>
                            <div class="col">
                                <div class="d-flex flex-column flex">
                                    <a href="#" class="text-body"><strong class="text-15pt">Call Alex</strong></a>


                                    <small class="text-muted d-flex align-items-center"><i class="material-icons icon-16pt mr-1">phone</i> 202-555-0131</small>

                                </div>



                            </div>
                        </div>
                    </div>

                </div>

                <small class="text-dark-gray px-3 py-1">
                    <strong>Tuesday, 26 Feb</strong>
                </small>

                <div class="list-group list-group-flush">

                    <div class="list-group-item bg-light">
                        <div class="row">
                            <div class="col-auto d-flex flex-column">
                                <small>03:13 PM</small>
                                <small class="text-dark-gray">2 hrs</small>
                            </div>
                            <div class="col">
                                <div class="d-flex flex-column flex">
                                    <a href="#" class="text-body"><strong class="text-15pt">Design Team Meeting</strong></a>

                                    <small class="text-muted d-flex align-items-center"><i class="material-icons icon-16pt mr-1">location_on</i> 16845 Hicks Road</small>


                                </div>
                                <div class="avatar-group mt-2">

                                    <div class="avatar avatar-xs">
                                        <img src="{% static 'assets/images/256_rsz_1andy-lee-642320-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                    </div>

                                    <div class="avatar avatar-xs">
                                        <img src="{% static 'assets/images/256_michael-dam-258165-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                    </div>

                                    <div class="avatar avatar-xs">
                                        <img src="{% static 'assets/images/256_luke-porter-261779-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                    </div>

                                    <div class="avatar avatar-xs">
                                        <img src="{% static 'assets/images/stories/256_rsz_clem-onojeghuo-193397-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                <small class="text-dark-gray px-3 py-1">
                    <strong>Monday, 25 Feb</strong>
                </small>

                <div class="list-group list-group-flush">

                    <div class="list-group-item bg-light">
                        <div class="row">
                            <div class="col-auto d-flex flex-column">
                                <small>12:30 PM</small>
                                <small class="text-dark-gray">2 hrs</small>
                            </div>
                            <div class="col d-flex">
                                <div class="d-flex flex-column flex">
                                    <a href="#" class="text-body"><strong class="text-15pt">Call Wendy</strong></a>


                                    <small class="text-muted d-flex align-items-center"><i class="material-icons icon-16pt mr-1">phone</i> 202-555-0131</small>

                                </div>


                                <div class="avatar avatar-xs">
                                    <img src="{% static 'assets/images/256_michael-dam-258165-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                </div>


                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>

    <!-- App Settings FAB -->
    <div id="app-settings">
        <app-settings layout-active="default" :layout-location="{
      'default': 'student-dashboard.html',
      'fixed': 'fixed-student-dashboard.html',
      'fluid': 'fluid-student-dashboard.html',
      'mini': 'mini-student-dashboard.html'
    }"></app-settings>
    </div>

    <!-- jQuery -->
    <script src="{% static 'assets/vendor/jquery.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'assets/vendor/popper.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap.min.js' %}"></script>

    <!-- Perfect Scrollbar -->
    <script src="{% static 'assets/vendor/perfect-scrollbar.min.js' %}"></script>

    <!-- DOM Factory -->
    <script src="{% static 'assets/vendor/dom-factory.js' %}"></script>

    <!-- MDK -->
    <script src="{% static 'assets/vendor/material-design-kit.js' %}"></script>

    <!-- Range Slider -->
    <script src="{% static 'assets/vendor/ion.rangeSlider.min.js' %}"></script>
    <script src="{% static 'assets/js/ion-rangeslider.js' %}"></script>

    <!-- App -->
    <script src="{% static 'assets/js/toggle-check-all.js' %}"></script>
    <script src="{% static 'assets/js/check-selected-row.js' %}"></script>
    <script src="{% static 'assets/js/dropdown.js' %}"></script>
    <script src="{% static 'assets/js/sidebar-mini.js' %}"></script>
    <script src="{% static 'assets/js/app.js' %}"></script>

    <!-- App Settings (safe to remove) -->
    <script src="{% static 'assets/js/app-settings.js' %}"></script>




</body>

</html>

templates/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">

{% include 'head.html' %}


<body class="layout-default">



{% include 'header2.html' %}

<div class="mdk-header-layout__content">

    <div class="mdk-drawer-layout js-mdk-drawer-layout" data-push data-responsive-width="992px">
        <div class="mdk-drawer-layout__content page">



            <div class="container-fluid page__heading-container">
                <div class="page__heading d-flex flex-column flex-md-row align-items-center justify-content-center justify-content-lg-between text-center text-lg-left">
                    <h1 class="m-lg-0">{% block name %}{% endblock name %}</h1>
                 
                </div>
            </div>
        
        
        
        
            {% block content %}{% endblock content %}
        
        </div>
        <!-- // END drawer-layout__content -->

        <div class="mdk-drawer  js-mdk-drawer" id="default-drawer" data-align="start">
            <div class="mdk-drawer__content">
                <div class="sidebar sidebar-light sidebar-left bg-white" data-perfect-scrollbar>


                    <div class="sidebar-block p-0 m-0">
                        <div class="d-flex align-items-center sidebar-p-a border-bottom bg-light">
                            <a href="#" class="flex d-flex align-items-center text-body text-underline-0">
                                <span class="avatar avatar-sm mr-2">
                                    <span class="avatar-title rounded-circle bg-soft-secondary text-muted">AD</span>
                                </span>
                                <span class="flex d-flex flex-column">
                                    {% if request.user.is_authenticated %}

                                    <strong>{{request.user.first_name}} {{request.user.last_name}}</strong>


                                    <small class="text-muted text-uppercase">Instructor</small>

                                    {% endif %}
                                </span>
                            </a>
                            <div class="dropdown ml-auto">
                                <a href="#" data-toggle="dropdown" data-caret="false" class="text-muted"><i class="material-icons">more_vert</i></a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="{% url 'instructor:instructor' %}">Dashboard</a>
                            
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" rel="nofollow" data-method="delete" href="login.html">Logout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sidebar-block p-0">

                           
                        <li class="sidebar-menu-item">
                            <a class="sidebar-menu-button" href="{% url 'instructor:instructor' %}">
                                <i class="sidebar-menu-icon sidebar-menu-icon--left material-icons">tab</i>
                                <span class="sidebar-menu-text">Dashboard</span>
                            </a>
                        </li>
                          
                            <li class="sidebar-menu-item">
                                <a class="sidebar-menu-button" href="{% url 'instructor:createQuiz' %}">
                                    <i class="sidebar-menu-icon sidebar-menu-icon--left material-icons">tab</i>
                                    <span class="sidebar-menu-text">Create A Quiz</span>
                                </a>
                            </li>
                          
                        
                        
                        </ul>

    
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- // END drawer-layout -->

</div>

    <div class="mdk-drawer js-mdk-drawer" id="events-drawer" data-align="end">
        <div class="mdk-drawer__content">
            <div class="sidebar sidebar-light sidebar-left" data-perfect-scrollbar>




                <small class="text-dark-gray px-3 py-1">
                    <strong>Thursday, 28 Feb</strong>
                </small>

                <div class="list-group list-group-flush">

                    <div class="list-group-item bg-light">
                        <div class="row">
                            <div class="col-auto d-flex flex-column">
                                <small>12:30 PM</small>
                                <small class="text-dark-gray">2 hrs</small>
                            </div>
                            <div class="col">
                                <div class="d-flex flex-column flex">
                                    <a href="#" class="text-body"><strong class="text-15pt">Marketing Team Meeting</strong></a>

                                    <small class="text-muted d-flex align-items-center"><i class="material-icons icon-16pt mr-1">location_on</i> 16845 Hicks Road</small>


                                </div>
                                <div class="avatar-group mt-2">

                                    <div class="avatar avatar-xs">
                                        <img src="{% static 'assets/images/256_joao-silas-636453-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                    </div>

                                    <div class="avatar avatar-xs">
                                        <img src="{% static 'assets/images/256_jeremy-banks-798787-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                    </div>

                                    <div class="avatar avatar-xs">
                                        <img src="{% static 'assets/images/256_daniel-gaffey-1060698-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                <small class="text-dark-gray px-3 py-1">
                    <strong>Wednesday, 27 Feb</strong>
                </small>

                <div class="list-group list-group-flush">

                    <div class="list-group-item bg-light">
                        <div class="row">
                            <div class="col-auto d-flex flex-column">
                                <small>07:48 PM</small>
                                <small class="text-dark-gray">30 min</small>
                            </div>
                            <div class="col">
                                <div class="d-flex flex-column flex">
                                    <a href="#" class="text-body"><strong class="text-15pt">Call Alex</strong></a>


                                    <small class="text-muted d-flex align-items-center"><i class="material-icons icon-16pt mr-1">phone</i> 202-555-0131</small>

                                </div>



                            </div>
                        </div>
                    </div>

                </div>

                <small class="text-dark-gray px-3 py-1">
                    <strong>Tuesday, 26 Feb</strong>
                </small>

                <div class="list-group list-group-flush">

                    <div class="list-group-item bg-light">
                        <div class="row">
                            <div class="col-auto d-flex flex-column">
                                <small>03:13 PM</small>
                                <small class="text-dark-gray">2 hrs</small>
                            </div>
                            <div class="col">
                                <div class="d-flex flex-column flex">
                                    <a href="#" class="text-body"><strong class="text-15pt">Design Team Meeting</strong></a>

                                    <small class="text-muted d-flex align-items-center"><i class="material-icons icon-16pt mr-1">location_on</i> 16845 Hicks Road</small>


                                </div>
                                <div class="avatar-group mt-2">

                                    <div class="avatar avatar-xs">
                                        <img src="{% static 'assets/images/256_rsz_1andy-lee-642320-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                    </div>

                                    <div class="avatar avatar-xs">
                                        <img src="{% static 'assets/images/256_michael-dam-258165-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                    </div>

                                    <div class="avatar avatar-xs">
                                        <img src="{% static 'assets/images/256_luke-porter-261779-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                    </div>

                                    <div class="avatar avatar-xs">
                                        <img src="{% static 'assets/images/stories/256_rsz_clem-onojeghuo-193397-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                <small class="text-dark-gray px-3 py-1">
                    <strong>Monday, 25 Feb</strong>
                </small>

                <div class="list-group list-group-flush">

                    <div class="list-group-item bg-light">
                        <div class="row">
                            <div class="col-auto d-flex flex-column">
                                <small>12:30 PM</small>
                                <small class="text-dark-gray">2 hrs</small>
                            </div>
                            <div class="col d-flex">
                                <div class="d-flex flex-column flex">
                                    <a href="#" class="text-body"><strong class="text-15pt">Call Wendy</strong></a>


                                    <small class="text-muted d-flex align-items-center"><i class="material-icons icon-16pt mr-1">phone</i> 202-555-0131</small>

                                </div>


                                <div class="avatar avatar-xs">
                                    <img src="{% static 'assets/images/256_michael-dam-258165-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                                </div>


                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>

    <!-- App Settings FAB -->
    <div id="app-settings">
        <app-settings layout-active="default" :layout-location="{
      'default': 'student-dashboard.html',
      'fixed': 'fixed-student-dashboard.html',
      'fluid': 'fluid-student-dashboard.html',
      'mini': 'mini-student-dashboard.html'
    }"></app-settings>
    </div>

    <!-- jQuery -->
    <script src="{% static 'assets/vendor/jquery.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'assets/vendor/popper.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap.min.js' %}"></script>

    <!-- Perfect Scrollbar -->
    <script src="{% static 'assets/vendor/perfect-scrollbar.min.js' %}"></script>

    <!-- DOM Factory -->
    <script src="{% static 'assets/vendor/dom-factory.js' %}"></script>

    <!-- MDK -->
    <script src="{% static 'assets/vendor/material-design-kit.js' %}"></script>

    <!-- Range Slider -->
    <script src="{% static 'assets/vendor/ion.rangeSlider.min.js' %}"></script>
    <script src="{% static 'assets/js/ion-rangeslider.js' %}"></script>

    <!-- App -->
    <script src="{% static 'assets/js/toggle-check-all.js' %}"></script>
    <script src="{% static 'assets/js/check-selected-row.js' %}"></script>
    <script src="{% static 'assets/js/dropdown.js' %}"></script>
    <script src="{% static 'assets/js/sidebar-mini.js' %}"></script>
    <script src="{% static 'assets/js/app.js' %}"></script>

    <!-- App Settings (safe to remove) -->
    <script src="{% static 'assets/js/app-settings.js' %}"></script>




</body>

</html>

templates/head.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dashboard</title>

    <!-- Prevent the demo from appearing in search engines -->
    <meta name="robots" content="noindex">

    <!-- Perfect Scrollbar -->
    <link type="text/css" href="{% static 'assets/vendor/perfect-scrollbar.css' %}" rel="stylesheet">

    <!-- App CSS -->
    <link type="text/css" href="{% static 'assets/css/app.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'assets/css/app.rtl.css' %}" rel="stylesheet">

    <!-- Material Design Icons -->
    <link type="text/css" href="{% static 'assets/css/vendor-material-icons.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'assets/css/vendor-material-icons.rtl.css' %}" rel="stylesheet">

    <!-- Font Awesome FREE Icons -->
    <link type="text/css" href="{% static 'assets/css/vendor-fontawesome-free.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'assets/css/vendor-fontawesome-free.rtl.css' %}" rel="stylesheet">

    <!-- ion Range Slider -->
    <link type="text/css" href="{% static 'assets/css/vendor-ion-rangeslider.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'assets/css/vendor-ion-rangeslider.rtl.css' %}" rel="stylesheet">


    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-115115077-3"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-115115077-3');
    </script>

    <!-- Facebook Pixel Code -->
    <script>
        ! function(f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function() {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '257843818545228');
        fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=257843818545228&ev=PageView&noscript=1" /></noscript>
    <!-- End Facebook Pixel Code -->





</head>

templates/headerContent.html
{% load static %}

        <!-- Header Layout Content -->
     
        <!-- // END header-layout__content -->

    </div>
    <!-- // END header-layout -->