config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls',namespace="accounts")),
    path("students/",include("student.urls",namespace="student")),
    path("instructor/",include("instructor.urls",namespace="instructor"))
]


if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instructor/urls.py
from django.urls import path
from .views import instructor,createQuiz,createQestion,createQuizChoices,deleteQuiz

app_name = "instructor"

urlpatterns = [
    path("",instructor,name="instructor"),
    path("createQuiz/",createQuiz,name="createQuiz"),
    path("createQestion/",createQestion,name="createQestion"),
    path("createQuizChoices/",createQuizChoices,name="createQuizChoices"),
    path("deleteQuiz/<int:id>/",deleteQuiz,name="deleteQuiz")
]

instructor/models.py
from django.db import models
from accounts.models import UserTable

# Create your models here.


class QuizTopic(models.Model):
    user = models.ForeignKey(UserTable,on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    attempts = models.PositiveBigIntegerField(default=0)
    passed = models.PositiveBigIntegerField(default=0)
    failed = models.PositiveBigIntegerField(default=0)


    def __str__(self) -> str:
        return self.title



class Quiz(models.Model):
    topic = models.ForeignKey(QuizTopic,on_delete=models.CASCADE,blank=True,null=True)
    quiz = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.quiz
    


class Choises(models.Model):
    quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE)
    choise = models.CharField(max_length=255)
    answer = models.BooleanField(default=False)

    def __str__(self) -> str:
        return str(self.choise)


    

instructor/views.py
from django.shortcuts import render,redirect
from django.db.models import Sum
from .form import (
    QuestionForm,
    QuestionCreate
)

from .models import (
    QuizTopic,
    Quiz,
    Choises
)

# Create your views here.


def instructor(request):
    all_topics = QuizTopic.objects.filter(user =  request.user)


    context = {
        'topics' : all_topics,
        'total_quiz' : len(all_topics),
        'passed':QuizTopic.objects.filter(user =  request.user).aggregate(Sum('passed'))['passed__sum'],
        'failed':QuizTopic.objects.filter(user =  request.user).aggregate(Sum('failed'))['failed__sum'],
        
    }



    return render(request,'instructor-dashboard.html',context)


def createQuiz(request):

 
    
    bb = request.session['topic'] 





    login_form = QuestionForm(request.POST,None)
    question = QuestionCreate(request.POST,None)
  

    if bb is not None:

        jui = QuizTopic.objects.get(id = int(bb))
        qqy = Quiz.objects.filter(topic = jui)

        choises = Choises.objects.all()

        context = {
        'question' : login_form,
        "topic" : jui.title,
        "quiz":question,
        "all_quizes" : qqy,
        "choices":choises
        }

        if request.method == "POST":
            obj = QuizTopic.objects.create (
                user = request.user,
                title = request.POST.get("question")
            )

            if obj is not None:
                request.session['topic'] = obj.id

                context = {
                    'question' : login_form,
                    "topic" : obj.title,
                    "quiz":question,
                     "all_quizes" : qqy,
                       "choices":choises
                }
                return render(request,'createQuiz.html',context)


        return render(request,'createQuiz.html',context)



    else:

        context = {
        'question' : login_form,
        "topic" : "",
        "quiz":question,
        "all_quizes" : []
    }



    
    
        if request.method == "POST":
            obj = QuizTopic.objects.create (
                user = request.user,
                title = request.POST.get("question")
            )

            
            

            if obj is not None:
                request.session['topic'] = obj.id
                qqy = Quiz.objects.filter(topic = obj)

                context = {
                    'question' : login_form,
                    "topic" : obj.title,
                    "quiz":question,
                    "all_quizes" : qqy
                }
                return render(request,'createQuiz.html',context)


        return render(request,'createQuiz.html',context)



def createQestion(request):
    if request.method == "POST":

        bb = request.session['topic'] 

        if bb is not None:
            jui = QuizTopic.objects.get(id = int(bb))

            ss = Quiz.objects.create(
                topic = jui,
                quiz = request.POST.get("quiz")
            )

            if ss is not None:
                return redirect("instructor:createQuiz")



def createQuizChoices(request):
    if request.method == "POST":
        quiz_number = request.POST.get("quiz_number")
        input_ = request.POST.get("input")
        answer = request.POST.get("questioncorrect_answer_id")

        if answer is not None:
            if "on" in answer.lower():

                get_q = Quiz.objects.get(id = int(quiz_number))
                choise = Choises.objects.create(
                    quiz = get_q,
                    choise = input_,
                    answer = True
                )

                if choise is not None:
                    return redirect("instructor:createQuiz")
        else:
            get_q = Quiz.objects.get(id = int(quiz_number))
            choise = Choises.objects.create(
                quiz = get_q,
                choise = input_
                
            )

            if choise is not None:
                return redirect("instructor:createQuiz")


        return redirect("instructor:createQuiz")



def deleteQuiz(request,id):
    Quiz.objects.get(id = int(id)).delete()
    return redirect("instructor:createQuiz")



        
        

instructor/templates/createQuiz.html
{% extends 'base2.html' %}
{% load static %}


{% block content %}

<div class="container-fluid page__heading-container">
    <div class="page__heading d-flex flex-column flex-md-row align-items-center justify-content-center justify-content-lg-between text-center text-lg-left">
        {% if topic %}
        <h1 class="m-lg-0">{{topic}} :: Topic</h1>
        {% endif %}
        
        
      
    </div>
</div>





<div class="container-fluid page__container">


    <div class="card">
        <div class="card-body card-form__body">
            <form action="{% url 'instructor:createQuiz' %}" method="POST">
                {% csrf_token %} 
                <div class="form-group mb-3">
                    <label class="control-label h6">New Topic:</label>
                    {{question.question}}
                </div>
                <button class="btn btn-primary"><i class="material-icons">add</i> Create Topic</button>
            </form>
        </div>
    </div>



    <div class="card">
        <div class="card-body card-form__body">
            <form action="{% url 'instructor:createQestion' %}" method="POST">
                {% csrf_token %} 
                <div class="form-group mb-3">
                    <label class="control-label h6">New Question:</label>
                    {{quiz.quiz}}
                </div>
                <button class="btn btn-primary"><i class="material-icons">add</i> Create Quesrion</button>
            </form>
        </div>
    </div>
    <div id="questions_wrapper">


        {% if all_quizes %}

        {% for u in  all_quizes %}
        
        <div class="card mb-4" data-position="1" data-question-id="1">
            <form action="{% url 'instructor:createQuizChoices' %}" method = "POST">
                {% csrf_token %} 
            <div class="card-header d-flex justify-content-between">
                <div class="d-flex align-items-center ">

                    <span class="question_handle btn btn-sm btn-secondary">
                        <i class="material-icons">menu</i>
                    </span>
                    <div class="h4 m-0 ml-4">Q: {{u.quiz}}</div>
                </div>
                <div>
                    <a href="{% url 'instructor:deleteQuiz'  u.id %}" class="btn btn-danger btn-sm">Delete</a>
                </div>
            </div>
            <div class="card-body">

                <div id="answerWrapper_1" class="mb-4">
                    <div class="row mb-1">
                        <div class="col"><strong></strong></div>
                        <div class="col text-right"><strong>Correct</strong></div>
                    </div>

                    
                        <div class="form-group mb-3">
                            <label class="control-label h6">Add Answer</label>
                            <input name="input" type="text" class="form-control" />
                            <input name="quiz_number" type="hidden" value="{{u.id}}" class="form-control" />
                        </div>
                        
                        <ul class="list-group" id="answer_container_1">
                            <li class="list-group-item d-flex" data-position="1" data-answer-id="1" data-question-id="1">
                                <span class="mr-2"><i class="material-icons text-light-gray">menu</i></span>
                                <div>
                                    Is This Answer?
                                </div>
                                <div class="ml-auto">
                                    <input type="radio" name="questioncorrect_answer_id" id="correct_answer_1" >
                                </div>
                            </li>
                        
                        </ul>


                        <label style="margin-top:10px !important" class="control-label h6">Answer Choices</label>

                        <ul class="list-group" id="answer_container_1">
                            {% if choices %}
                             {% for r in choices  %}
                             {% if r.quiz.id == u.id %}
                             {% if r.answer %}
                             <li class="list-group-item d-flex" data-position="1" data-answer-id="1" data-question-id="1">
                               
                                <div style="color:green !important">
                                    {{r.choise}}
                                </div>
                                
                            </li>
                             {% else %}

                             <li class="list-group-item d-flex" data-position="1" data-answer-id="1" data-question-id="1">
                               
                                <div>
                                    {{r.choise}}
                                </div>
                                
                            </li>
                             {% endif %}
                             
                             
                             {% endif %}
                            
                             {% endfor %}
                            
                            {% endif %}
                           
                            
                        </ul>
                
                </div>




                <div class="">
               
                        <div class="form-group mb-0">
                            <button class="btn btn-success">New Answer</button>
                        </div>
                    
                </div>
          
            </div>
        </form>
        </div>

        {% endfor %}
        
        
        {% endif %}

        


      

        


    </div>
</div>


{% endblock content %}

instructor/templates/instructor-dashboard.html
{% extends 'base2.html' %}
{% load static %}


{% block content %}


<div class="container-fluid page__heading-container">
    <div class="page__heading d-flex flex-column flex-md-row align-items-center justify-content-center justify-content-lg-between text-center text-lg-left">
        <h1 class="m-lg-0">Instructor Dashboard</h1>
   
    </div>
</div>





<div class="container-fluid page__container">

    <div class="row card-group-row">
        <div class="col-lg-4 col-md-6 card-group-row__col">
            <div class="card card-group-row__card card-body card-body-x-lg flex-row align-items-center">
                <div class="flex">
                    <div class="card-header__title text-muted mb-2">Total Quiz</div>
                    <div class="text-amount">{{total_quiz}}</div>
                
                </div>

                <div class="avatar">
                    <span class="bg-soft-success avatar-title rounded-circle text-center text-success">
                        <i class="material-icons icon-40pt">gps_fixed</i>
                    </span>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 card-group-row__col">
            <div class="card card-group-row__card card-body card-body-x-lg flex-row align-items-center">
                <div class="flex">
                    <div class="card-header__title text-muted mb-2">Passed Quiz</div>
                    <div class="text-amount">{{passed}}</div>
                </div>
                <div class="avatar">
                    <span class="bg-soft-primary avatar-title rounded-circle text-center text-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 40 40" width="30" height="30">
                            <g transform="matrix(1.6666666666666667,0,0,1.6666666666666667,0,0)">
                                <path d="M16,5.75c0.414,0,0.75-0.336,0.75-0.75V3.5c0-0.414-0.336-0.75-0.75-0.75s-0.75,0.336-0.75,0.75V5 C15.25,5.414,15.586,5.75,16,5.75z M21,3c0-1.657-1.343-3-3-3H6C4.343,0,3,1.343,3,3v18c0,1.657,1.343,3,3,3h12 c1.657,0,3-1.343,3-3V3z M12,14c0.552,0,1,0.448,1,1s-0.448,1-1,1s-1-0.448-1-1S11.448,14,12,14z M11,10.5c0-0.552,0.448-1,1-1 s1,0.448,1,1s-0.448,1-1,1S11,11.052,11,10.5z M16.5,18.75c0.414,0,0.75,0.336,0.75,0.75s-0.336,0.75-0.75,0.75H11 c-0.414,0-0.75-0.336-0.75-0.75s0.336-0.75,0.75-0.75H16.5z M16.5,16c-0.552,0-1-0.448-1-1s0.448-1,1-1c0.552,0,1,0.448,1,1 S17.052,16,16.5,16z M16.5,11.5c-0.552,0-1-0.448-1-1s0.448-1,1-1c0.552,0,1,0.448,1,1S17.052,11.5,16.5,11.5z M7.5,16 c-0.552,0-1-0.448-1-1s0.448-1,1-1s1,0.448,1,1S8.052,16,7.5,16z M8.5,19.5c0,0.552-0.448,1-1,1s-1-0.448-1-1s0.448-1,1-1 S8.5,18.948,8.5,19.5z M7.5,11.5c-0.552,0-1-0.448-1-1s0.448-1,1-1s1,0.448,1,1S8.052,11.5,7.5,11.5z M6,2h12c0.552,0,1,0.448,1,1 v3.25c0,0.138-0.112,0.25-0.25,0.25H5.25C5.112,6.5,5,6.388,5,6.25V3C5,2.448,5.448,2,6,2z" stroke="none" fill="currentColor" stroke-width="0" stroke-linecap="round" stroke-linejoin="round"></path>
                            </g>
                        </svg>
                    </span>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-12 card-group-row__col">
            <div class="card card-group-row__card card-body card-body-x-lg flex-row align-items-center">
                <div class="flex">
                    <div class="card-header__title text-muted mb-2">Failed Quiz</div>
                    <div class="text-amount">{{failed}}</div>
                   
                </div>
                <div class="avatar">
                    <span class="bg-soft-warning avatar-title rounded-circle text-center text-warning">
                        <i class="material-icons text-warning icon-40pt">perm_identity</i>
                    </span>
                </div>
            </div>
        </div>
    </div>

    <!-- CHART -->
    <div class="row">
    
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-large bg-light d-flex align-items-center">

                    <h4 class="card-header__title">Quizes</h4>

                </div>




                <ul class="list-group list-group-flush mb-0" style="z-index: initial;">


                    {% if topics %}
                    {% for k in  topics %}
                    <li class="list-group-item" style="z-index: initial;">
                        <div class="d-flex align-items-center">
                          
                            <div class="flex">
                                <a href="#" class="text-body"><strong>{{k.title}}</strong></a>
                                <div class="d-flex align-items-center">
                                    <small class="text-muted">{{k.attempts}} Attempts</small>
                                </div>
                            </div>
                        
                        </div>
                    </li>
                    {% endfor %}
                    {% endif %}
                  

                </ul>
            </div>

        </div>
    </div>
</div>
{% endblock content %}